
name: pulse
description: Music app with Firebase Auth, Firestore, playlist, lyrics
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.9.2
  just_audio: ^0.9.34
  audio_service: ^0.18.11
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
